import type { Metadata } from "next";
import { ReduxProvider } from "@/redux/provider";
import StyledComponentsRegistry from "../utils/AntdRegistry";

import { Inter } from "next/font/google";

import "./globals.css";
import "../styles/antd.css";

import HeaderProvider from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <StyledComponentsRegistry>
            <HeaderProvider />
            <div
              style={{
                width: "100%",
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                padding:'82px'
              }}
            >
              {children}
            </div>
          </StyledComponentsRegistry>
        </ReduxProvider>
      </body>
    </html>
  );
}
